services:
  backend:
    image: ghcr.io/mak5er/joke-site-backend
    build:
      context: ./joke-site-backend
    env_file:
      - ./joke-site-backend/.env
    restart: always
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/mak5er/joke-site-frontend
    build:
      context: ./joke-site-frontend
    env_file:
      - ./joke-site-frontend/.env
    restart: always
    ports:
      - "3000:3000"
