version: '3.8'

services:
  backend:
    build:
      context: ./joke-site-backend
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./joke-site-frontend
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"

