name: Build and Push Multi-Platform Docker Images to GHCR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --allow-insecure-entitlement network.host

      - name: Convert repository owner to lowercase
        id: lower
        run: echo "LOWER_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform backend image
        uses: docker/build-push-action@v4
        with:
          context: ./joke-site-backend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.LOWER_OWNER }}/joke-site-backend:latest

      - name: Build and push multi-platform frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./joke-site-frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.LOWER_OWNER }}/joke-site-frontend:latest
